-- MySQL Script generated by MySQL Workbench
-- Sat Aug 22 10:30:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sql_easygo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sql_easygo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql_easygo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sql_easygo` ;

-- -----------------------------------------------------
-- Table `sql_easygo`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`address` (
  `address_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `first_name` VARCHAR(10) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `phone_number` VARCHAR(11) NOT NULL,
  `area` VARCHAR(30) NOT NULL,
  `detail_address` VARCHAR(30) NOT NULL,
  `is_default` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`admin` (
  `admin_id` INT(11) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`bill` (
  `bill_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `icon_url` VARCHAR(200) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `create_time` DATE NOT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`bill_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`category` (
  `category_id` INT(11) NOT NULL,
  `store_id` INT(11) NOT NULL,
  `category_name` VARCHAR(20) NOT NULL,
  `category_desc` VARCHAR(200) NOT NULL,
  `priority` INT(11) NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`classify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`classify` (
  `classify_id` INT(11) NOT NULL,
  `img_url` VARCHAR(200) NOT NULL,
  `classify_desc` VARCHAR(200) NOT NULL,
  `sort` INT(11) NOT NULL,
  PRIMARY KEY (`classify_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`collect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`collect` (
  `collect_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `store_id` INT(11) NOT NULL,
  PRIMARY KEY (`collect_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`message` (
  `message_id` INT(11) NOT NULL,
  `send_id` INT(11) NOT NULL,
  `receive_id` INT(11) NOT NULL,
  `send_type` VARCHAR(30) NOT NULL,
  `receive_type` VARCHAR(30) NOT NULL,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `send_time` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`message_id`),
  UNIQUE INDEX `send_id_UNIQUE` (`send_id` ASC) VISIBLE,
  UNIQUE INDEX `receive_id_UNIQUE` (`receive_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`order` (
  `order_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `store_id` INT(11) NOT NULL,
  `buyer_name` VARCHAR(30) NOT NULL,
  `buyer_phone` VARCHAR(11) NOT NULL,
  `buyer_address` VARCHAR(200) NOT NULL,
  `order_amount` DECIMAL(8,2) NOT NULL,
  `order_status` VARCHAR(10) NOT NULL,
  `pay_status` VARCHAR(10) NOT NULL,
  `pay_time` DATE NULL DEFAULT NULL,
  `sent_time` DATE NULL DEFAULT NULL,
  `arrived_time` DATE NULL DEFAULT NULL,
  `finish_time` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`order_detail` (
  `order_detail_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `produce_id` INT(11) NOT NULL,
  `produce_name` VARCHAR(200) NOT NULL,
  `produce_price` DECIMAL(8,2) NOT NULL,
  `produce_quantity` INT(11) NOT NULL,
  `produce_icon` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`order_detail_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  UNIQUE INDEX `produce_id_UNIQUE` (`produce_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`produce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`produce` (
  `produce_id` INT(11) NOT NULL,
  `store_id` INT(11) NOT NULL,
  `classify_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  `produce_name` VARCHAR(200) NOT NULL,
  `produce_price` DECIMAL(8,2) NOT NULL,
  `produce_desc` VARCHAR(200) NOT NULL,
  `produce_icon` VARCHAR(200) NOT NULL,
  `produce_status` VARCHAR(30) NOT NULL,
  `produce_stock` INT(11) NOT NULL,
  `produce_imgs` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`produce_id`),
  UNIQUE INDEX `store_id_UNIQUE` (`store_id` ASC) VISIBLE,
  UNIQUE INDEX `classify_id_UNIQUE` (`classify_id` ASC) VISIBLE,
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`shopping_cart` (
  `shopping_cart_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `produce_id` INT(11) NOT NULL,
  `produce_name` VARCHAR(30) NOT NULL,
  `produce_price` DECIMAL(8,2) NOT NULL,
  `produce_quantity` INT(11) NOT NULL,
  `produce_icon` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`shopping_cart_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `produce_id_UNIQUE` (`produce_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`store` (
  `store_id` INT(11) NOT NULL,
  `storekeeper_id` INT(11) NOT NULL,
  `classify_id` INT(11) NOT NULL,
  `store_name` VARCHAR(30) NOT NULL,
  `store_desc` VARCHAR(200) NOT NULL,
  `store_anno` VARCHAR(1000) NULL DEFAULT NULL,
  `store_icon` VARCHAR(200) NOT NULL,
  `background_url` VARCHAR(200) NOT NULL,
  `store_location` VARCHAR(16) NOT NULL,
  `store_address` VARCHAR(60) NOT NULL,
  `store_phone` VARCHAR(11) NOT NULL,
  `store_status` VARCHAR(10) NOT NULL,
  `store_integrity` INT(3) NOT NULL DEFAULT '100',
  `business_license` VARCHAR(255) NULL DEFAULT NULL,
  `store_sign` VARCHAR(255) NULL DEFAULT NULL,
  `store_front` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`store_id`),
  UNIQUE INDEX `storekeeper_id_UNIQUE` (`storekeeper_id` ASC) VISIBLE,
  UNIQUE INDEX `classify_id_UNIQUE` (`classify_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`storekeeper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`storekeeper` (
  `storekeeper_id` INT(11) NOT NULL,
  `storekeeper_name` VARCHAR(30) NOT NULL,
  `phone_number` VARCHAR(11) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `identity_number` VARCHAR(18) NOT NULL,
  `email` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`storekeeper_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_easygo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_easygo`.`user` (
  `user_id` INT(11) NOT NULL,
  `user_name` VARCHAR(30) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `points` DECIMAL(8,2) NOT NULL,
  `user_type` INT(11) NOT NULL DEFAULT '1',
  `user_icon` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
